//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateManager.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAccount
    {
        public System.Guid Id { get; set; }
        public System.Guid AccountId { get; set; }
        public System.Guid ContactId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Contact Contact { get; set; }
    }
}
