//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstateManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Здравейте {0},&lt;/p&gt;
        ///&lt;p&gt;Изпращаме Ви това писмо, защото получихме заявка, че сте забравили паролата си и искате да я смените.&lt;/p&gt;
        ///&lt;b&gt;Ако Вие не сте поискали това, можете да игнорирате това писмо.&lt;/b&gt;
        ///&lt;p&gt;Ако заявката идва от Вас, кликнете на този линк:&lt;p&gt;
        ///&lt;br/&gt;
        ///&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;П.С.: Това е автоматично генерирано писмо. Моля не му отговаряйте.&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Поздрави,&lt;/p&gt;
        ///&lt;p&gt;RealEstateManger&lt;/p&gt;.
        /// </summary>
        public static string AgentForgottenPasswordEmail_Body {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealEstateManager - Възстановяване на акаунт при забравена парола.
        /// </summary>
        public static string AgentForgottenPasswordEmail_Subject {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на акаунт при забравена парола.
        /// </summary>
        public static string AgentForgottenPasswordForm_Header {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишете e-mail адреса на акаунта си и ще получите линк към страницата, на която да смените паролата си..
        /// </summary>
        public static string AgentForgottenPasswordForm_RecoveryDescription {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordForm_RecoveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        public static string AgentForgottenPasswordForm_SubmitButtonText {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordForm_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string AgentForgottenPasswordModel_EmailAddress {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на забравена парола.
        /// </summary>
        public static string AgentForgottenPasswordPage_Title {
            get {
                return ResourceManager.GetString("AgentForgottenPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за агент.
        /// </summary>
        public static string AgentIndexForm_Header {
            get {
                return ResourceManager.GetString("AgentIndexForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за агент.
        /// </summary>
        public static string AgentIndexPage_Title {
            get {
                return ResourceManager.GetString("AgentIndexPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string AgentInfoModel_EmailAddress {
            get {
                return ResourceManager.GetString("AgentInfoModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string AgentInfoModel_Password {
            get {
                return ResourceManager.GetString("AgentInfoModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string AgentInfoModel_PhoneNumber {
            get {
                return ResourceManager.GetString("AgentInfoModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string AgentInfoModel_Username {
            get {
                return ResourceManager.GetString("AgentInfoModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string AgentLoginForm_ForgottenPassword {
            get {
                return ResourceManager.GetString("AgentLoginForm_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в системата.
        /// </summary>
        public static string AgentLoginForm_Header {
            get {
                return ResourceManager.GetString("AgentLoginForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string AgentLoginForm_SubmitButtonText {
            get {
                return ResourceManager.GetString("AgentLoginForm_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string AgentLoginModel_Email {
            get {
                return ResourceManager.GetString("AgentLoginModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string AgentLoginModel_Password {
            get {
                return ResourceManager.GetString("AgentLoginModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string AgentLoginModel_RememberMe {
            get {
                return ResourceManager.GetString("AgentLoginModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string AgentLoginPage_Title {
            get {
                return ResourceManager.GetString("AgentLoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете нова парола.
        /// </summary>
        public static string AgentRecoverPasswordForm_Header {
            get {
                return ResourceManager.GetString("AgentRecoverPasswordForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден токен за възстановяване на акаунт..
        /// </summary>
        public static string AgentRecoverPasswordModel_InvalidToken_Error {
            get {
                return ResourceManager.GetString("AgentRecoverPasswordModel_InvalidToken_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола.
        /// </summary>
        public static string AgentRecoverPasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("AgentRecoverPasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на акаунт.
        /// </summary>
        public static string AgentRecoverPasswordPage_Title {
            get {
                return ResourceManager.GetString("AgentRecoverPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този e-mail адрес вече е регистриран. Моля изберете друг..
        /// </summary>
        public static string AgentRegister_EmailAddressExists_Error {
            get {
                return ResourceManager.GetString("AgentRegister_EmailAddressExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден ключ за регистрация на брокер..
        /// </summary>
        public static string AgentRegister_IncorrectKey_Error {
            get {
                return ResourceManager.GetString("AgentRegister_IncorrectKey_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това потребителско име вече е регистрирано. Моля изберете друго..
        /// </summary>
        public static string AgentRegister_UsernameExists_Error {
            get {
                return ResourceManager.GetString("AgentRegister_UsernameExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на брокер.
        /// </summary>
        public static string AgentRegisterForm_Header {
            get {
                return ResourceManager.GetString("AgentRegisterForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string AgentRegisterModel_EmailAddress {
            get {
                return ResourceManager.GetString("AgentRegisterModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string AgentRegisterModel_FirstName {
            get {
                return ResourceManager.GetString("AgentRegisterModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string AgentRegisterModel_LastName {
            get {
                return ResourceManager.GetString("AgentRegisterModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string AgentRegisterModel_Password {
            get {
                return ResourceManager.GetString("AgentRegisterModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string AgentRegisterModel_PhoneNumber {
            get {
                return ResourceManager.GetString("AgentRegisterModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационен ключ.
        /// </summary>
        public static string AgentRegisterModel_RegistrationKey {
            get {
                return ResourceManager.GetString("AgentRegisterModel_RegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string AgentRegisterModel_Username {
            get {
                return ResourceManager.GetString("AgentRegisterModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string AgentRegisterPage_Title {
            get {
                return ResourceManager.GetString("AgentRegisterPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealEstateManager.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string HomeOperationSuccessfulPage_ReturnToHome {
            get {
                return ResourceManager.GetString("HomeOperationSuccessfulPage_ReturnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операцията е успешна.
        /// </summary>
        public static string HomeOperationSuccessfulPage_Title {
            get {
                return ResourceManager.GetString("HomeOperationSuccessfulPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден e-mail или парола..
        /// </summary>
        public static string InvalidLoginDetailsError {
            get {
                return ResourceManager.GetString("InvalidLoginDetailsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string MenuButton_AgentLogin {
            get {
                return ResourceManager.GetString("MenuButton_AgentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string MenuButton_AgentLogout {
            get {
                return ResourceManager.GetString("MenuButton_AgentLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това поле е задължително..
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
    }
}
