//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstateManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Account_TableHeader_EmailAddress {
            get {
                return ResourceManager.GetString("Account_TableHeader_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Account_TableHeader_Number {
            get {
                return ResourceManager.GetString("Account_TableHeader_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string Account_TableHeader_Operations {
            get {
                return ResourceManager.GetString("Account_TableHeader_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Account_TableHeader_Type {
            get {
                return ResourceManager.GetString("Account_TableHeader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Account_TableHeader_Username {
            get {
                return ResourceManager.GetString("Account_TableHeader_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокиране на съществуващ акаунт.
        /// </summary>
        public static string AccountDeletePage_Header {
            get {
                return ResourceManager.GetString("AccountDeletePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте, че искате да блокирате акаунта?.
        /// </summary>
        public static string AccountDeletePage_Text {
            get {
                return ResourceManager.GetString("AccountDeletePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокиране на акаунт.
        /// </summary>
        public static string AccountDeletePage_Title {
            get {
                return ResourceManager.GetString("AccountDeletePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички потребители.
        /// </summary>
        public static string AccountIndexPage_Header {
            get {
                return ResourceManager.GetString("AccountIndexPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        public static string AccountIndexPage_Search {
            get {
                return ResourceManager.GetString("AccountIndexPage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители.
        /// </summary>
        public static string AccountIndexPage_Title {
            get {
                return ResourceManager.GetString("AccountIndexPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealEstateManager.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден брой балкони. Те трябва да бъдат положително число..
        /// </summary>
        public static string BuildingInfoCreation_IncorrectBalconies_Error {
            get {
                return ResourceManager.GetString("BuildingInfoCreation_IncorrectBalconies_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден брой бани. Те трябва да бъдат положително число..
        /// </summary>
        public static string BuildingInfoCreation_IncorrectBathrooms_Error {
            get {
                return ResourceManager.GetString("BuildingInfoCreation_IncorrectBathrooms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден брой спални. Те трябва да бъдат положително число..
        /// </summary>
        public static string BuildingInfoCreation_IncorrectBedrooms_Error {
            get {
                return ResourceManager.GetString("BuildingInfoCreation_IncorrectBedrooms_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден брой етажи. Те трябва да бъдат един или повече..
        /// </summary>
        public static string BuildingInfoCreation_IncorrectFloors_Error {
            get {
                return ResourceManager.GetString("BuildingInfoCreation_IncorrectFloors_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден брой гаражи. Те трябва да бъдат положително число..
        /// </summary>
        public static string BuildingInfoCreation_IncorrectGarages_Error {
            get {
                return ResourceManager.GetString("BuildingInfoCreation_IncorrectGarages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на детайли за имот.
        /// </summary>
        public static string BuildingInfoCreationPage_Header {
            get {
                return ResourceManager.GetString("BuildingInfoCreationPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на детайли.
        /// </summary>
        public static string BuildingInfoCreationPage_Title {
            get {
                return ResourceManager.GetString("BuildingInfoCreationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на детайли за имот.
        /// </summary>
        public static string BuildingInfoDeletePage_Header {
            get {
                return ResourceManager.GetString("BuildingInfoDeletePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте че искате да изтриете детайлите за имота?.
        /// </summary>
        public static string BuildingInfoDeletePage_Text {
            get {
                return ResourceManager.GetString("BuildingInfoDeletePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на детайли.
        /// </summary>
        public static string BuildingInfoDeletePage_Title {
            get {
                return ResourceManager.GetString("BuildingInfoDeletePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за информацията на имота.
        /// </summary>
        public static string BuildingInfoDetailsPage_Title {
            get {
                return ResourceManager.GetString("BuildingInfoDetailsPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акт 16.
        /// </summary>
        public static string BuildingInfoModel_Act16 {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Act16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой Балкони/Тераси.
        /// </summary>
        public static string BuildingInfoModel_Balconies {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Balconies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой Бани.
        /// </summary>
        public static string BuildingInfoModel_Bathrooms {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Bathrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой Спални.
        /// </summary>
        public static string BuildingInfoModel_Bedrooms {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Bedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой Етажи.
        /// </summary>
        public static string BuildingInfoModel_Floors {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Floors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Брой Гаражи.
        /// </summary>
        public static string BuildingInfoModel_Garages {
            get {
                return ResourceManager.GetString("BuildingInfoModel_Garages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изглед.
        /// </summary>
        public static string BuildingInfoModel_View {
            get {
                return ResourceManager.GetString("BuildingInfoModel_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на детайлите за имот.
        /// </summary>
        public static string BuildingInfoUpdatePage_Header {
            get {
                return ResourceManager.GetString("BuildingInfoUpdatePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на детайли.
        /// </summary>
        public static string BuildingInfoUpdatePage_Title {
            get {
                return ResourceManager.GetString("BuildingInfoUpdatePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Блокирай.
        /// </summary>
        public static string Button_Ban {
            get {
                return ResourceManager.GetString("Button_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създай.
        /// </summary>
        public static string Button_Create {
            get {
                return ResourceManager.GetString("Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтрий.
        /// </summary>
        public static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли.
        /// </summary>
        public static string Button_Details {
            get {
                return ResourceManager.GetString("Button_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай.
        /// </summary>
        public static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирай Инфо.
        /// </summary>
        public static string Button_Edit_Info {
            get {
                return ResourceManager.GetString("Button_Edit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Права.
        /// </summary>
        public static string Button_Edit_Rights {
            get {
                return ResourceManager.GetString("Button_Edit_Rights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпрати.
        /// </summary>
        public static string Button_Submit {
            get {
                return ResourceManager.GetString("Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обнови.
        /// </summary>
        public static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това поле съдържа невалиден e-mail..
        /// </summary>
        public static string EmailFormatError {
            get {
                return ResourceManager.GetString("EmailFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площ.
        /// </summary>
        public static string Estate_TableHeader_Area {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Estate_TableHeader_Name {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер.
        /// </summary>
        public static string Estate_TableHeader_Number {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string Estate_TableHeader_Operations {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Estate_TableHeader_Price {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Estate_TableHeader_Status {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Estate_TableHeader_Type {
            get {
                return ResourceManager.GetString("Estate_TableHeader_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Права.
        /// </summary>
        public static string EstateAccountCreationPage_Title {
            get {
                return ResourceManager.GetString("EstateAccountCreationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Има права.
        /// </summary>
        public static string EstateAccountModel_HasRights {
            get {
                return ResourceManager.GetString("EstateAccountModel_HasRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на правата.
        /// </summary>
        public static string EstateAccountUpdatePage_Header {
            get {
                return ResourceManager.GetString("EstateAccountUpdatePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма регистрирани Агенти в системата..
        /// </summary>
        public static string EstateAccountUpdatePage_NoRegisteredAgents_Error {
            get {
                return ResourceManager.GetString("EstateAccountUpdatePage_NoRegisteredAgents_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на правата на агентите.
        /// </summary>
        public static string EstateAccountUpdatePage_Text {
            get {
                return ResourceManager.GetString("EstateAccountUpdatePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имот на този адрес е вече регистриран..
        /// </summary>
        public static string EstateCreation_AddressExists_Error {
            get {
                return ResourceManager.GetString("EstateCreation_AddressExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна площ. Тя трябва да бъде положително число..
        /// </summary>
        public static string EstateCreation_IncorrectArea_Error {
            get {
                return ResourceManager.GetString("EstateCreation_IncorrectArea_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидна цена. Тя трябва да бъде положително число..
        /// </summary>
        public static string EstateCreation_IncorrectPrice_Error {
            get {
                return ResourceManager.GetString("EstateCreation_IncorrectPrice_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това име вече съществува. Моля изберете друго..
        /// </summary>
        public static string EstateCreation_NameExists_Error {
            get {
                return ResourceManager.GetString("EstateCreation_NameExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображения.
        /// </summary>
        public static string EstateCreationModel_Images {
            get {
                return ResourceManager.GetString("EstateCreationModel_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавяне на нов имот.
        /// </summary>
        public static string EstateCreationPage_Header {
            get {
                return ResourceManager.GetString("EstateCreationPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Създаване на имот.
        /// </summary>
        public static string EstateCreationPage_Title {
            get {
                return ResourceManager.GetString("EstateCreationPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на съществуващ имот.
        /// </summary>
        public static string EstateDeletePage_Header {
            get {
                return ResourceManager.GetString("EstateDeletePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сигурни ли сте че искате да изтриете имота?.
        /// </summary>
        public static string EstateDeletePage_Text {
            get {
                return ResourceManager.GetString("EstateDeletePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изтриване на имот.
        /// </summary>
        public static string EstateDeletePage_Title {
            get {
                return ResourceManager.GetString("EstateDeletePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за имот.
        /// </summary>
        public static string EstateDetailsPage_Header {
            get {
                return ResourceManager.GetString("EstateDetailsPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Галерия.
        /// </summary>
        public static string EstateGetModel_ImagePaths {
            get {
                return ResourceManager.GetString("EstateGetModel_ImagePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кв. м..
        /// </summary>
        public static string EstateIndexPage_AreaSign {
            get {
                return ResourceManager.GetString("EstateIndexPage_AreaSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички имоти.
        /// </summary>
        public static string EstateIndexPage_Header {
            get {
                return ResourceManager.GetString("EstateIndexPage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to лв..
        /// </summary>
        public static string EstateIndexPage_MoneySign {
            get {
                return ResourceManager.GetString("EstateIndexPage_MoneySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Търсене.
        /// </summary>
        public static string EstateIndexPage_Search {
            get {
                return ResourceManager.GetString("EstateIndexPage_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имоти.
        /// </summary>
        public static string EstateIndexPage_Title {
            get {
                return ResourceManager.GetString("EstateIndexPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string EstateModel_Address {
            get {
                return ResourceManager.GetString("EstateModel_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площ.
        /// </summary>
        public static string EstateModel_Area {
            get {
                return ResourceManager.GetString("EstateModel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string EstateModel_Name {
            get {
                return ResourceManager.GetString("EstateModel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string EstateModel_Price {
            get {
                return ResourceManager.GetString("EstateModel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поверително описание.
        /// </summary>
        public static string EstateModel_PrivateDescription {
            get {
                return ResourceManager.GetString("EstateModel_PrivateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публично описание.
        /// </summary>
        public static string EstateModel_PublicDescription {
            get {
                return ResourceManager.GetString("EstateModel_PublicDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string EstateModel_Status {
            get {
                return ResourceManager.GetString("EstateModel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string EstateModel_Type {
            get {
                return ResourceManager.GetString("EstateModel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съществуващи изображения.
        /// </summary>
        public static string EstateUpdateModel_ImagePaths {
            get {
                return ResourceManager.GetString("EstateUpdateModel_ImagePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нови изображения.
        /// </summary>
        public static string EstateUpdateModel_Images {
            get {
                return ResourceManager.GetString("EstateUpdateModel_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на съществуващ имот.
        /// </summary>
        public static string EstateUpdatePage_Header {
            get {
                return ResourceManager.GetString("EstateUpdatePage_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновяване на имот.
        /// </summary>
        public static string EstateUpdatePage_Title {
            get {
                return ResourceManager.GetString("EstateUpdatePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string HomeOperationSuccessfulPage_ReturnToHome {
            get {
                return ResourceManager.GetString("HomeOperationSuccessfulPage_ReturnToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операцията е успешна.
        /// </summary>
        public static string HomeOperationSuccessfulPage_Title {
            get {
                return ResourceManager.GetString("HomeOperationSuccessfulPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден e-mail или парола..
        /// </summary>
        public static string InvalidLoginDetails_Error {
            get {
                return ResourceManager.GetString("InvalidLoginDetails_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имоти.
        /// </summary>
        public static string MenuButton_Estates {
            get {
                return ResourceManager.GetString("MenuButton_Estates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нов имот.
        /// </summary>
        public static string MenuButton_Estates_Create {
            get {
                return ResourceManager.GetString("MenuButton_Estates_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всички имоти.
        /// </summary>
        public static string MenuButton_Estates_ViewAll {
            get {
                return ResourceManager.GetString("MenuButton_Estates_ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string MenuButton_Logout {
            get {
                return ResourceManager.GetString("MenuButton_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребители.
        /// </summary>
        public static string MenuButton_Users {
            get {
                return ResourceManager.GetString("MenuButton_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Няма записи, които да бъдат показани за вашата заявка..
        /// </summary>
        public static string NoEntriesFound_Error {
            get {
                return ResourceManager.GetString("NoEntriesFound_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница {0} от {1}.
        /// </summary>
        public static string Pagination_Summary {
            get {
                return ResourceManager.GetString("Pagination_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Здравейте {0},&lt;/p&gt;
        ///&lt;p&gt;Изпращаме Ви това писмо, защото получихме заявка, че сте забравили паролата си и искате да я смените.&lt;/p&gt;
        ///&lt;b&gt;Ако Вие не сте поискали това, можете да игнорирате това писмо.&lt;/b&gt;
        ///&lt;p&gt;Ако заявката идва от Вас, кликнете на този линк:&lt;p&gt;
        ///&lt;br/&gt;
        ///&lt;a href=&quot;{1}&quot;&gt;{1}&lt;/a&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;П.С.: Това е автоматично генерирано писмо. Моля не му отговаряйте.&lt;/p&gt;
        ///&lt;br/&gt;
        ///&lt;p&gt;Поздрави,&lt;/p&gt;
        ///&lt;p&gt;RealEstateManger&lt;/p&gt;.
        /// </summary>
        public static string Public_AccountForgottenPasswordEmail_Body {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordEmail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RealEstateManager - Възстановяване на акаунт при забравена парола.
        /// </summary>
        public static string Public_AccountForgottenPasswordEmail_Subject {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на акаунт при забравена парола.
        /// </summary>
        public static string Public_AccountForgottenPasswordForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Напишете e-mail адреса на акаунта си и ще получите линк към страницата, на която да смените паролата си..
        /// </summary>
        public static string Public_AccountForgottenPasswordForm_RecoveryDescription {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordForm_RecoveryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изпращане.
        /// </summary>
        public static string Public_AccountForgottenPasswordForm_SubmitButtonText {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordForm_SubmitButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountForgottenPasswordModel_EmailAddress {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на забравена парола.
        /// </summary>
        public static string Public_AccountForgottenPasswordPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountForgottenPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за агент.
        /// </summary>
        public static string Public_AccountIndexForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountIndexForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детайли за агент.
        /// </summary>
        public static string Public_AccountIndexPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountIndexPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountInfoModel_EmailAddress {
            get {
                return ResourceManager.GetString("Public_AccountInfoModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Public_AccountInfoModel_Password {
            get {
                return ResourceManager.GetString("Public_AccountInfoModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string Public_AccountInfoModel_PhoneNumber {
            get {
                return ResourceManager.GetString("Public_AccountInfoModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Public_AccountInfoModel_Username {
            get {
                return ResourceManager.GetString("Public_AccountInfoModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забравена парола.
        /// </summary>
        public static string Public_AccountLoginForm_ForgottenPassword {
            get {
                return ResourceManager.GetString("Public_AccountLoginForm_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход в системата.
        /// </summary>
        public static string Public_AccountLoginForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountLoginForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountLoginModel_Email {
            get {
                return ResourceManager.GetString("Public_AccountLoginModel_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Public_AccountLoginModel_Password {
            get {
                return ResourceManager.GetString("Public_AccountLoginModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомни ме.
        /// </summary>
        public static string Public_AccountLoginModel_RememberMe {
            get {
                return ResourceManager.GetString("Public_AccountLoginModel_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Public_AccountLoginPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountLoginPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведете нова парола.
        /// </summary>
        public static string Public_AccountRecoverPasswordForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountRecoverPasswordForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден токен за възстановяване на акаунт..
        /// </summary>
        public static string Public_AccountRecoverPasswordModel_InvalidToken_Error {
            get {
                return ResourceManager.GetString("Public_AccountRecoverPasswordModel_InvalidToken_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова парола.
        /// </summary>
        public static string Public_AccountRecoverPasswordModel_NewPassword {
            get {
                return ResourceManager.GetString("Public_AccountRecoverPasswordModel_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Възстановяване на акаунт.
        /// </summary>
        public static string Public_AccountRecoverPasswordPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountRecoverPasswordPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Този e-mail адрес вече е регистриран. Моля изберете друг..
        /// </summary>
        public static string Public_AccountRegister_EmailAddressExists_Error {
            get {
                return ResourceManager.GetString("Public_AccountRegister_EmailAddressExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалиден регистрационен ключ..
        /// </summary>
        public static string Public_AccountRegister_IncorrectKey_Error {
            get {
                return ResourceManager.GetString("Public_AccountRegister_IncorrectKey_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това потребителско име вече е регистрирано. Моля изберете друго..
        /// </summary>
        public static string Public_AccountRegister_UsernameExists_Error {
            get {
                return ResourceManager.GetString("Public_AccountRegister_UsernameExists_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на администратор.
        /// </summary>
        public static string Public_AccountRegisterAdminForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_EmailAddress {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_FirstName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_LastName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_Password {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_PhoneNumber {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационен ключ за администратор.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_RegistrationKey {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_RegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Public_AccountRegisterAdminModel_Username {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Public_AccountRegisterAdminPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAdminPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на агент.
        /// </summary>
        public static string Public_AccountRegisterAgentForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_EmailAddress {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_FirstName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_LastName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_Password {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_PhoneNumber {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрационен ключ за агент.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_RegistrationKey {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_RegistrationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Public_AccountRegisterAgentModel_Username {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Public_AccountRegisterAgentPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountRegisterAgentPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на потребител.
        /// </summary>
        public static string Public_AccountRegisterPublicUserForm_Header {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserForm_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail адрес.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_EmailAddress {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_FirstName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_LastName {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Парола.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_Password {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Телефонен номер.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_PhoneNumber {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителско име.
        /// </summary>
        public static string Public_AccountRegisterPublicUserModel_Username {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserModel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Public_AccountRegisterPublicUserPage_Title {
            get {
                return ResourceManager.GetString("Public_AccountRegisterPublicUserPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площ.
        /// </summary>
        public static string Public_Estate_SortingLabel_Area {
            get {
                return ResourceManager.GetString("Public_Estate_SortingLabel_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Име.
        /// </summary>
        public static string Public_Estate_SortingLabel_Name {
            get {
                return ResourceManager.GetString("Public_Estate_SortingLabel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Public_Estate_SortingLabel_Price {
            get {
                return ResourceManager.GetString("Public_Estate_SortingLabel_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string Public_Estate_SortingLabel_Status {
            get {
                return ResourceManager.GetString("Public_Estate_SortingLabel_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Public_Estate_SortingLabel_Type {
            get {
                return ResourceManager.GetString("Public_Estate_SortingLabel_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административен панел.
        /// </summary>
        public static string Public_MenuButton_AdminArea {
            get {
                return ResourceManager.GetString("Public_MenuButton_AdminArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        public static string Public_MenuButton_Login {
            get {
                return ResourceManager.GetString("Public_MenuButton_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изход.
        /// </summary>
        public static string Public_MenuButton_Logout {
            get {
                return ResourceManager.GetString("Public_MenuButton_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Public_MenuButton_Register {
            get {
                return ResourceManager.GetString("Public_MenuButton_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        public static string Public_RealEstateManager_Models_Data_UserType_Admin {
            get {
                return ResourceManager.GetString("Public_RealEstateManager_Models_Data_UserType_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Агент.
        /// </summary>
        public static string Public_RealEstateManager_Models_Data_UserType_Agent {
            get {
                return ResourceManager.GetString("Public_RealEstateManager_Models_Data_UserType_Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публичен.
        /// </summary>
        public static string Public_RealEstateManager_Models_Data_UserType_PublicUser {
            get {
                return ResourceManager.GetString("Public_RealEstateManager_Models_Data_UserType_PublicUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изток.
        /// </summary>
        public static string RealEstateManager_Models_Data_BuildingViewType_East {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_BuildingViewType_East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Север.
        /// </summary>
        public static string RealEstateManager_Models_Data_BuildingViewType_North {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_BuildingViewType_North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юг.
        /// </summary>
        public static string RealEstateManager_Models_Data_BuildingViewType_South {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_BuildingViewType_South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запад.
        /// </summary>
        public static string RealEstateManager_Models_Data_BuildingViewType_West {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_BuildingViewType_West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Под наем.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateStatusType_ForRent {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateStatusType_ForRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to За продан.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateStatusType_ForSale {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateStatusType_ForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отдаден под наем.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateStatusType_RentedOut {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateStatusType_RentedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продаден.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateStatusType_Sold {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateStatusType_Sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Апартамент.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateType_Apartment {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateType_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Къща.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateType_House {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateType_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Земя.
        /// </summary>
        public static string RealEstateManager_Models_Data_EstateType_Land {
            get {
                return ResourceManager.GetString("RealEstateManager_Models_Data_EstateType_Land", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Това поле е задължително..
        /// </summary>
        public static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
    }
}
